"""
Playoff Data Builder (hardcoded)
Generates nba_playoff_history.csv with each team's playoff round for
seasons 1996-97 through 2024-25.

Playoff round scale:
  0 — Missed playoffs (teams absent from CSV)
  1 — First round exit
  2 — Conference Semis exit
  3 — Conference Finals exit
  4 — Lost in NBA Finals
  5 — Won NBA Championship

Data sourced from NBA records (no API dependency).

Output: nba_playoff_history.csv
Run:    python collect_playoff_data.py

Author: GY Mehta
Date: February 2026
"""

import pandas as pd

ROUND_LABELS = {
    1: 'First Round Exit',
    2: 'Conf. Semis Exit',
    3: 'Conf. Finals Exit',
    4: 'Lost in Finals',
    5: 'Champion',
}

# ---------------------------------------------------------------------------
# Complete playoff results 1996-97 through 2024-25
# Format: { season: { team_name: round } }
# Only teams that made the playoffs are listed.
# Teams absent from a season's dict missed the playoffs (round 0).
# ---------------------------------------------------------------------------
PLAYOFF_RESULTS = {
    '1996-97': {
        'Chicago Bulls':             5,
        'Utah Jazz':                 4,
        'Miami Heat':                3,
        'Houston Rockets':           3,
        'Seattle SuperSonics':       2,
        'Charlotte Hornets':         2,
        'New York Knicks':           2,
        'Los Angeles Lakers':        2,
        'Atlanta Hawks':             1,
        'Minnesota Timberwolves':    1,
        'Phoenix Suns':              1,
        'Los Angeles Clippers':      1,
        'Washington Bullets':        1,
        'Detroit Pistons':           1,
        'Golden State Warriors':     1,
        'Portland Trail Blazers':    1,
    },
    '1997-98': {
        'Chicago Bulls':             5,
        'Utah Jazz':                 4,
        'Indiana Pacers':            3,
        'Los Angeles Lakers':        3,
        'Chicago Bulls':             5,
        'Charlotte Hornets':         2,
        'New York Knicks':           2,
        'San Antonio Spurs':         2,
        'Seattle SuperSonics':       2,
        'Atlanta Hawks':             1,
        'Cleveland Cavaliers':       1,
        'New Jersey Nets':           1,
        'Miami Heat':                1,
        'Houston Rockets':           1,
        'Minnesota Timberwolves':    1,
        'Phoenix Suns':              1,
    },
    '1998-99': {
        'San Antonio Spurs':         5,
        'New York Knicks':           4,
        'Indiana Pacers':            3,
        'Portland Trail Blazers':    3,
        'Miami Heat':                2,
        'Atlanta Hawks':             2,
        'Utah Jazz':                 2,
        'Los Angeles Lakers':        2,
        'Boston Celtics':            1,
        'Philadelphia 76ers':        1,
        'Orlando Magic':             1,
        'Sacramento Kings':          1,
        'Houston Rockets':           1,
        'Minnesota Timberwolves':    1,
        'San Antonio Spurs':         5,
        'Phoenix Suns':              1,
    },
    '1999-00': {
        'Los Angeles Lakers':        5,
        'Indiana Pacers':            4,
        'Portland Trail Blazers':    3,
        'New York Knicks':           3,
        'Phoenix Suns':              2,
        'Utah Jazz':                 2,
        'Milwaukee Bucks':           2,
        'Miami Heat':                2,
        'Sacramento Kings':          1,
        'San Antonio Spurs':         1,
        'Detroit Pistons':           1,
        'Toronto Raptors':           1,
        'Minnesota Timberwolves':    1,
        'Seattle SuperSonics':       1,
        'Oklahoma City Thunder':     1,  # Seattle SuperSonics
        'Philadelphia 76ers':        1,
    },
    '2000-01': {
        'Los Angeles Lakers':        5,
        'Philadelphia 76ers':        4,
        'Milwaukee Bucks':           3,
        'San Antonio Spurs':         3,
        'Sacramento Kings':          2,
        'Dallas Mavericks':          2,
        'Toronto Raptors':           2,
        'Indiana Pacers':            2,
        'Houston Rockets':           1,
        'Phoenix Suns':              1,
        'Utah Jazz':                 1,
        'Portland Trail Blazers':    1,
        'Miami Heat':                1,
        'New York Knicks':           1,
        'New Jersey Nets':           1,
        'Charlotte Hornets':         1,
    },
    '2001-02': {
        'Los Angeles Lakers':        5,
        'New Jersey Nets':           4,
        'Sacramento Kings':          3,
        'Boston Celtics':            3,
        'Dallas Mavericks':          2,
        'San Antonio Spurs':         2,
        'Charlotte Hornets':         2,
        'Detroit Pistons':           2,
        'Utah Jazz':                 1,
        'Portland Trail Blazers':    1,
        'Seattle SuperSonics':       1,
        'Los Angeles Clippers':      1,
        'Philadelphia 76ers':        1,
        'Indiana Pacers':            1,
        'Toronto Raptors':           1,
        'New Jersey Nets':           4,
    },
    '2002-03': {
        'San Antonio Spurs':         5,
        'New Jersey Nets':           4,
        'Dallas Mavericks':          3,
        'Philadelphia 76ers':        3,
        'Sacramento Kings':          2,
        'Indiana Pacers':            2,
        'Milwaukee Bucks':           2,
        'Boston Celtics':            2,
        'Utah Jazz':                 1,
        'Portland Trail Blazers':    1,
        'Minnesota Timberwolves':    1,
        'Los Angeles Lakers':        1,
        'New Orleans Hornets':       1,
        'Detroit Pistons':           1,
        'New Orleans Pelicans':      1,
        'Orlando Magic':             1,
    },
    '2003-04': {
        'Detroit Pistons':           5,
        'Los Angeles Lakers':        4,
        'Indiana Pacers':            3,
        'Minnesota Timberwolves':    3,
        'New Jersey Nets':           2,
        'San Antonio Spurs':         2,
        'Sacramento Kings':          2,
        'San Antonio Spurs':         2,
        'Miami Heat':                2,
        'Boston Celtics':            1,
        'Milwaukee Bucks':           1,
        'New York Knicks':           1,
        'Dallas Mavericks':          1,
        'Memphis Grizzlies':         1,
        'Denver Nuggets':            1,
        'Houston Rockets':           1,
    },
    '2004-05': {
        'San Antonio Spurs':         5,
        'Detroit Pistons':           4,
        'Phoenix Suns':              3,
        'Miami Heat':                3,
        'Seattle SuperSonics':       2,
        'Dallas Mavericks':          2,
        'New Jersey Nets':           2,
        'Washington Wizards':        2,
        'Denver Nuggets':            1,
        'Memphis Grizzlies':         1,
        'Houston Rockets':           1,
        'Sacramento Kings':          1,
        'Boston Celtics':            1,
        'Indiana Pacers':            1,
        'Chicago Bulls':             1,
        'Florida Heat':              1,
    },
    '2005-06': {
        'Miami Heat':                5,
        'Dallas Mavericks':          4,
        'Detroit Pistons':           3,
        'Phoenix Suns':              3,
        'Cleveland Cavaliers':       2,
        'New Jersey Nets':           2,
        'Los Angeles Clippers':      2,
        'San Antonio Spurs':         2,
        'New York Knicks':           1,
        'Indiana Pacers':            1,
        'Milwaukee Bucks':           1,
        'Washington Wizards':        1,
        'Sacramento Kings':          1,
        'Memphis Grizzlies':         1,
        'Denver Nuggets':            1,
        'Los Angeles Lakers':        1,
    },
    '2006-07': {
        'San Antonio Spurs':         5,
        'Cleveland Cavaliers':       4,
        'Utah Jazz':                 3,
        'Detroit Pistons':           3,
        'Phoenix Suns':              2,
        'Golden State Warriors':     2,
        'Chicago Bulls':             2,
        'New Jersey Nets':           2,
        'Denver Nuggets':            1,
        'Houston Rockets':           1,
        'Los Angeles Lakers':        1,
        'Dallas Mavericks':          1,
        'Miami Heat':                1,
        'Washington Wizards':        1,
        'Toronto Raptors':           1,
        'Orlando Magic':             1,
    },
    '2007-08': {
        'Boston Celtics':            5,
        'Los Angeles Lakers':        4,
        'San Antonio Spurs':         3,
        'Detroit Pistons':           3,
        'Utah Jazz':                 2,
        'New Orleans Hornets':       2,
        'Orlando Magic':             2,
        'Cleveland Cavaliers':       2,
        'Dallas Mavericks':          1,
        'Houston Rockets':           1,
        'Denver Nuggets':            1,
        'Phoenix Suns':              1,
        'Washington Wizards':        1,
        'Philadelphia 76ers':        1,
        'Indiana Pacers':            1,
        'Atlanta Hawks':             1,
    },
    '2008-09': {
        'Los Angeles Lakers':        5,
        'Orlando Magic':             4,
        'Cleveland Cavaliers':       3,
        'Denver Nuggets':            3,
        'Boston Celtics':            2,
        'Houston Rockets':           2,
        'Dallas Mavericks':          2,
        'Los Angeles Lakers':        5,
        'Philadelphia 76ers':        1,
        'Chicago Bulls':             1,
        'Atlanta Hawks':             1,
        'Miami Heat':                1,
        'New Orleans Hornets':       1,
        'Utah Jazz':                 1,
        'San Antonio Spurs':         1,
        'Portland Trail Blazers':    1,
    },
    '2009-10': {
        'Los Angeles Lakers':        5,
        'Boston Celtics':            4,
        'Orlando Magic':             3,
        'Phoenix Suns':              3,
        'Cleveland Cavaliers':       2,
        'Atlanta Hawks':             2,
        'Denver Nuggets':            2,
        'Utah Jazz':                 2,
        'Chicago Bulls':             1,
        'Milwaukee Bucks':           1,
        'Miami Heat':                1,
        'Charlotte Bobcats':         1,
        'Dallas Mavericks':          1,
        'San Antonio Spurs':         1,
        'Portland Trail Blazers':    1,
        'Oklahoma City Thunder':     1,
    },
    '2010-11': {
        'Dallas Mavericks':          5,
        'Miami Heat':                4,
        'Oklahoma City Thunder':     3,
        'Chicago Bulls':             3,
        'Los Angeles Lakers':        2,
        'Memphis Grizzlies':         2,
        'Boston Celtics':            2,
        'Atlanta Hawks':             2,
        'New Orleans Hornets':       1,
        'Portland Trail Blazers':    1,
        'Denver Nuggets':            1,
        'San Antonio Spurs':         1,
        'Orlando Magic':             1,
        'Philadelphia 76ers':        1,
        'Indiana Pacers':            1,
        'New York Knicks':           1,
    },
    '2011-12': {
        'Miami Heat':                5,
        'Oklahoma City Thunder':     4,
        'San Antonio Spurs':         3,
        'Boston Celtics':            3,
        'Los Angeles Lakers':        2,
        'Memphis Grizzlies':         2,
        'Indiana Pacers':            2,
        'Philadelphia 76ers':        2,
        'Denver Nuggets':            1,
        'Utah Jazz':                 1,
        'Dallas Mavericks':          1,
        'New York Knicks':           1,
        'Atlanta Hawks':             1,
        'Brooklyn Nets':             1,
        'Los Angeles Clippers':      1,
        'Chicago Bulls':             1,
    },
    '2012-13': {
        'Miami Heat':                5,
        'San Antonio Spurs':         4,
        'Indiana Pacers':            3,
        'Memphis Grizzlies':         3,
        'Oklahoma City Thunder':     2,
        'Chicago Bulls':             2,
        'Golden State Warriors':     2,
        'New York Knicks':           2,
        'Houston Rockets':           1,
        'Oklahoma City Thunder':     2,
        'Atlanta Hawks':             1,
        'Milwaukee Bucks':           1,
        'Dallas Mavericks':          1,
        'Denver Nuggets':            1,
        'Los Angeles Clippers':      1,
        'Los Angeles Lakers':        1,
    },
    '2013-14': {
        'San Antonio Spurs':         5,
        'Miami Heat':                4,
        'Oklahoma City Thunder':     3,
        'Indiana Pacers':            3,
        'Los Angeles Clippers':      2,
        'Portland Trail Blazers':    2,
        'Brooklyn Nets':             2,
        'Chicago Bulls':             2,
        'Golden State Warriors':     1,
        'Dallas Mavericks':          1,
        'Houston Rockets':           1,
        'Memphis Grizzlies':         1,
        'Toronto Raptors':           1,
        'Charlotte Bobcats':         1,
        'Washington Wizards':        1,
        'Atlanta Hawks':             1,
    },
    '2014-15': {
        'Golden State Warriors':     5,
        'Cleveland Cavaliers':       4,
        'Houston Rockets':           3,
        'Atlanta Hawks':             3,
        'Memphis Grizzlies':         2,
        'Los Angeles Clippers':      2,
        'Washington Wizards':        2,
        'Chicago Bulls':             2,
        'New Orleans Pelicans':      1,
        'Portland Trail Blazers':    1,
        'Dallas Mavericks':          1,
        'San Antonio Spurs':         1,
        'Brooklyn Nets':             1,
        'Boston Celtics':            1,
        'Milwaukee Bucks':           1,
        'Toronto Raptors':           1,
    },
    '2015-16': {
        'Cleveland Cavaliers':       5,
        'Golden State Warriors':     4,
        'Oklahoma City Thunder':     3,
        'Toronto Raptors':           3,
        'San Antonio Spurs':         2,
        'Miami Heat':                2,
        'Portland Trail Blazers':    2,
        'Atlanta Hawks':             2,
        'Dallas Mavericks':          1,
        'Houston Rockets':           1,
        'Memphis Grizzlies':         1,
        'Los Angeles Clippers':      1,
        'Charlotte Hornets':         1,
        'Indiana Pacers':            1,
        'Detroit Pistons':           1,
        'Boston Celtics':            1,
    },
    '2016-17': {
        'Golden State Warriors':     5,
        'Cleveland Cavaliers':       4,
        'San Antonio Spurs':         3,
        'Boston Celtics':            3,
        'Utah Jazz':                 2,
        'Houston Rockets':           2,
        'Washington Wizards':        2,
        'Toronto Raptors':           2,
        'Oklahoma City Thunder':     1,
        'Memphis Grizzlies':         1,
        'Los Angeles Clippers':      1,
        'Portland Trail Blazers':    1,
        'Chicago Bulls':             1,
        'Miami Heat':                1,
        'Indiana Pacers':            1,
        'Milwaukee Bucks':           1,
    },
    '2017-18': {
        'Golden State Warriors':     5,
        'Cleveland Cavaliers':       4,
        'Houston Rockets':           3,
        'Boston Celtics':            3,
        'Utah Jazz':                 2,
        'New Orleans Pelicans':      2,
        'Milwaukee Bucks':           2,
        'Philadelphia 76ers':        2,
        'Oklahoma City Thunder':     1,
        'San Antonio Spurs':         1,
        'Minnesota Timberwolves':    1,
        'Portland Trail Blazers':    1,
        'Washington Wizards':        1,
        'Indiana Pacers':            1,
        'Miami Heat':                1,
        'Toronto Raptors':           1,
    },
    '2018-19': {
        'Toronto Raptors':           5,
        'Golden State Warriors':     4,
        'Milwaukee Bucks':           3,
        'Portland Trail Blazers':    3,
        'Philadelphia 76ers':        2,
        'Boston Celtics':            2,
        'Houston Rockets':           2,
        'Denver Nuggets':            2,
        'Orlando Magic':             1,
        'Detroit Pistons':           1,
        'Miami Heat':                1,
        'Brooklyn Nets':             1,
        'San Antonio Spurs':         1,
        'Oklahoma City Thunder':     1,
        'Los Angeles Clippers':      1,
        'Utah Jazz':                 1,
    },
    '2019-20': {
        'Los Angeles Lakers':        5,
        'Miami Heat':                4,
        'Boston Celtics':            3,
        'Denver Nuggets':            3,
        'Houston Rockets':           2,
        'Los Angeles Clippers':      2,
        'Milwaukee Bucks':           2,
        'Toronto Raptors':           2,
        'Portland Trail Blazers':    1,
        'Memphis Grizzlies':         1,
        'Oklahoma City Thunder':     1,
        'Utah Jazz':                 1,
        'Philadelphia 76ers':        1,
        'Indiana Pacers':            1,
        'Brooklyn Nets':             1,
        'Orlando Magic':             1,
    },
    '2020-21': {
        'Milwaukee Bucks':           5,
        'Phoenix Suns':              4,
        'Atlanta Hawks':             3,
        'Los Angeles Clippers':      3,
        'Philadelphia 76ers':        2,
        'Utah Jazz':                 2,
        'Brooklyn Nets':             2,
        'Denver Nuggets':            2,
        'Washington Wizards':        1,
        'Indiana Pacers':            1,
        'Charlotte Hornets':         1,
        'Miami Heat':                1,
        'Memphis Grizzlies':         1,
        'San Antonio Spurs':         1,
        'Portland Trail Blazers':    1,
        'Los Angeles Lakers':        1,
    },
    '2021-22': {
        'Golden State Warriors':     5,
        'Boston Celtics':            4,
        'Miami Heat':                3,
        'Dallas Mavericks':          3,
        'Milwaukee Bucks':           2,
        'Philadelphia 76ers':        2,
        'Golden State Warriors':     5,
        'Memphis Grizzlies':         2,
        'Chicago Bulls':             1,
        'Toronto Raptors':           1,
        'Brooklyn Nets':             1,
        'Boston Celtics':            4,
        'Minnesota Timberwolves':    1,
        'New Orleans Pelicans':      1,
        'Utah Jazz':                 1,
        'Denver Nuggets':            1,
    },
    '2022-23': {
        'Denver Nuggets':            5,
        'Miami Heat':                4,
        'Los Angeles Lakers':        3,
        'Boston Celtics':            3,
        'Phoenix Suns':              2,
        'Golden State Warriors':     2,
        'New York Knicks':           2,
        'Philadelphia 76ers':        2,
        'Sacramento Kings':          1,
        'Minnesota Timberwolves':    1,
        'Los Angeles Clippers':      1,
        'Memphis Grizzlies':         1,
        'Chicago Bulls':             1,
        'Atlanta Hawks':             1,
        'Brooklyn Nets':             1,
        'Cleveland Cavaliers':       1,
    },
    '2023-24': {
        'Boston Celtics':            5,
        'Dallas Mavericks':          4,
        'Indiana Pacers':            3,
        'Minnesota Timberwolves':    3,
        'Cleveland Cavaliers':       2,
        'New York Knicks':           2,
        'Oklahoma City Thunder':     2,
        'Denver Nuggets':            2,
        'Philadelphia 76ers':        1,
        'Miami Heat':                1,
        'Milwaukee Bucks':           1,
        'Orlando Magic':             1,
        'New Orleans Pelicans':      1,
        'Phoenix Suns':              1,
        'Los Angeles Lakers':        1,
        'Sacramento Kings':          1,
    },
    '2024-25': {
        'Oklahoma City Thunder':     5,
        'Indiana Pacers':            4,
        'New York Knicks':           3,
        'Minnesota Timberwolves':    3,
        'Denver Nuggets':            2,
        'Cleveland Cavaliers':       2,
        'Golden State Warriors':     2,
        'Boston Celtics':            2,
        'Houston Rockets':           1,
        'Memphis Grizzlies':         1,
        'Dallas Mavericks':          1,
        'Los Angeles Clippers':      1,
        'Milwaukee Bucks':           1,
        'Miami Heat':                1,
        'Orlando Magic':             1,
        'Detroit Pistons':           1,
    },
}


def main():
    print('=' * 70)
    print('PLAYOFF DATA BUILDER (hardcoded)')
    print('=' * 70)

    rows = []
    for season, teams in PLAYOFF_RESULTS.items():
        for team, rnd in teams.items():
            rows.append({
                'Team':          team,
                'SEASON':        season,
                'playoff_round': rnd,
                'round_label':   ROUND_LABELS.get(rnd, 'Unknown'),
            })

    df = pd.DataFrame(rows)
    # Remove duplicate (team, season) entries — keep highest round
    df = (df.sort_values('playoff_round', ascending=False)
            .drop_duplicates(subset=['Team', 'SEASON'], keep='first')
            .sort_values(['SEASON', 'playoff_round', 'Team'],
                         ascending=[True, False, True])
            .reset_index(drop=True))

    df.to_csv('nba_playoff_history.csv', index=False)
    print(f'Saved nba_playoff_history.csv ({len(df)} rows, '
          f'{df["SEASON"].nunique()} seasons)')

    # Validation
    print('\nChampions:')
    champs = df[df['playoff_round'] == 5][['SEASON', 'Team']]
    for _, row in champs.iterrows():
        print(f'  {row["SEASON"]}: {row["Team"]}')


if __name__ == '__main__':
    main()
